name: Build Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
     - main
     - develop

jobs:
  build:
    name: Build Pokemon App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JavaScript Dependencies
        run: npm ci

      - name: Build Web App
        run: npm run build
  
  create-release:
    name: Create App Release
    runs-on: ubuntu-latest
    permissions:
        contents: write
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true